Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.provision "file", source: "~/Fakultet/CloudComputing/Git2/CloudComputing/WebApp", destination: "WebApp"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provision :shell, path: "provision_script.sh"
end
