version: "3.7"

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - vars.env
    ports:
      - "5433:5432"
    container_name: postgres

  django-app:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on: 
      - db

  