version: "3.7"

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "db"   
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    container_name: postgres



  django-app:
    build: .
    restart: unless-stopped
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on: 
      - db

    
  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./app.conf:/etc/nginx/conf.d/app.conf
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  